[tool.semantic_release]
commit_parser = "angular"
tag_format = "{version}"

[tool.semantic_release.branches.main]
match = "main"

[tool.semantic_release.branches.stable]
match = "stable/.*"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0