name: Feature Merge - Minor Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump-minor:
    if: github.event.head_commit.message != 'skip-ci'
    permissions:
      contents: write  # Required for creating branches and pushing changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history and tags

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Python Semantic Release
        id: semantic_release
        uses: python-semantic-release/python-semantic-release@v9.8.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: "false"
          changelog: "false"

      - name: Create branch for new version
        if: steps.semantic_release.outputs.released == 'true'
        run: |
          NEW_VERSION=$(echo "${{ steps.semantic_release.outputs.version }}" | awk -F. '{print "stable/"$1"."$2}')
          git fetch origin
          git checkout -b "$NEW_VERSION" main
          git push origin "$NEW_VERSION"