name: Feature Merge - Minor Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump-minor:
    if: github.event.head_commit.message != 'skip-ci'
    permissions:
      contents: write  # Required for creating branches and pushing changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history and tags

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create branch for new version
        if: steps.semantic_release.outputs.new_release_published == 'true'
        run: |
          NEW_VERSION=${{ steps.semantic_release.outputs.new_release_version }}
          git fetch origin
          git checkout -b "$NEW_VERSION" main
          git push origin "$NEW_VERSION"