name: Hotfix - Patch Version Bump and Dockerize

on:
  push:
    branches:
      - 'stable/**'

jobs:
  hotfix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for semantic-release

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Validate commit types (must only be 'fix')
        run: |
          COMMITS=$(git log origin/${{ github.ref_name }}..HEAD --pretty=format:"%s")
          echo "$COMMITS" | while read -r line; do
            if ! echo "$line" | grep -Eq '^fix(\([^)]+\))?: '; then
              echo "❌ Invalid commit for hotfix: $line"
              echo "💡 Only 'fix' type commits are allowed in hotfix branches (conventional commits)."
              exit 1
            fi
          done

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}