name: Hotfix - Patch Version Bump and Dockerize

on:
  push:
    branches:
      - 'release/**'

jobs:
  hotfix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for semantic-release

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.8.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: "false"
          changelog: "false"